import { Metadata } from '../interfaces/types';

export const swapAvaxUvd: Metadata = {
  baseUrl: 'https://sherry-minithon.onrender.com',
  url: 'https://chat.sherry.social/accounts/byparcero_',
  icon: 'https://sherry-minithon.onrender.com/public/img/swap_avax_uvd.jpeg',
  title: 'Swap AVAX for UVD',
  description: 'Swap AVAX tokens for Ultravioleta DAO Token UVD',
  actions: [
    {
      type: 'dynamic',
      label: 'Confirm Swap AVAX → UVD',
      description: 'Swap AVAX tokens for Ultravioleta DAO Token UVD',
      path: '/api/swap/swap-avax-uvd',
      chains: {
        source: 43114, // Avalanche C-Chain
      },
      params: [
        {
          name: 'protocol',
          type: 'text',
          label: 'Protocol',
          value: 'arena',
          required: true,
          minLength: 1,
          maxLength: 100,
          description: 'DEX protocol to use for the swap',
        },
        {
          name: 'chainId',
          type: 'number',
          label: 'Chain ID',
          value: 43114,
          required: true,
          description: 'Blockchain chain ID for the swap (Avalanche)',
        },
        {
          name: 'kolRouterAddress',
          type: 'text',
          label: 'Creator Code (Optional)',
          value: '0x09F078819Bd6af0586294d8F4c419C03b2FE2234',
          required: false,
          minLength: 1,
          maxLength: 100,
          description: 'Optional creator referral address for fee sharing',
        },
        {
          name: 'userAddress',
          type: 'text',
          label: 'User Address',
          value: 'sender',
          required: true,
          minLength: 1,
          maxLength: 100,
          description: 'User wallet address',
        },
        {
          name: 'fromToken',
          type: 'text',
          label: 'From Token',
          value: 'AVAX',
          required: true,
          minLength: 1,
          maxLength: 100,
          description: 'Token to send (AVAX)',
        },
        {
          name: 'toToken',
          type: 'text',
          label: 'To Token',
          value: 'UVD',
          required: true,
          minLength: 1,
          maxLength: 20,
          description: 'Token to receive (UVD)',
        },
        {
          name: 'amount',
          type: 'number',
          label: 'Enter Amount to Swap',
          required: true,
          min: 0.000001,
          description: 'Enter the amount of AVAX you want to swap',
        },
        {
          name: 'slippage',
          type: 'text',
          label: 'Slippage Tolerance (%)',
          value: '0.1',
          required: false,
          minLength: 1,
          maxLength: 100,
          description: 'Maximum price movement tolerance (recommended: 0.5-2%)',
        },
      ],
    },
  ],
};
